services:
  - type: web
    name: ag-harold-jose-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ACTIVE_CHANNEL_ID
        value: "@pruebajsj"
      - key: CHANNEL_ID
        value: "@AGHAROLDJOSE_BOT"
      - key: TEST_CHANNEL_ID
        value: "@pruebajsj"
      - key: TIMEZONE
        value: "America/Caracas"
